### PR TITLE
Merge code and notebooks for my SGF paper.

### PR DESCRIPTION
**Pull request by dtherrick**
This update has all code and sample notebooks for my paper and presentation as SGF 2019 / Dallas.

### CODE REVIEW

**Comment by cjdinger** [comment]
Your updates deleted/changed all of the other folders -- I'm not sure how to merge this as-is.  Usually you would fork the entire repo and change just your parts, and use pull request to merge those changes. All other areas would remain unchanged.  Can you revert and retry?

**Comment by cj13579** [comment]
It seems like [this](https://github.com/dtherrick/sas-global-forum-2019/commit/9dd8037c39718aba7348e35bee17018847cb4a59) is the commit that causes the issue.


@dtherrick I think the best thing to do here will be to do as @cjdinger says and revert back to master and then replay this. I don't know how familiar you are with Git but the way that I would do this would be as follows:

1. Create a new branch and checkout the latest commit from the source repo:
```git
git checkout -b herrick
git checkout 9dd8037
```
2. Cherry pick all of your commits _except_ the commit where you delete the rest of repository
```git
git cherry-pick a40d3a1 0f7d59c bedd3e7 ac33d29 4357830 6407ccc c594517 56660782 5bc1ce5 f70aac4 170d16f a205efa 28a28ac
```
3. Create your pull requet to the sascommunities repository using this new branch. You _may_ have to merge this new branch back into master. I'm not 100% sure.

**Comment by dtherrick** [comment]
sorry all - just seeing this now. need to check my notifications settings.

@cj13579, I'll give it a shot on my own repo, get it back to the right status this afternoon. Then I'll just create a new PR and we can go from there. Apologies for the confusion! That's what I get for trying to declutter my own space.

**Comment by dtherrick** [comment]
@cjdinger I should be up to date now, my repo is where I believe you want it to be. Can you take a look and see if there's anything I missed? If not I am all set to merge now.

Thanks!

**Review by cjdinger — CHANGES_REQUESTED** [review]
Closer! I think that these files still show as deleted from the root of the repo:

 CONTRIBUTING.md 
 ContributorAgreement.pdf 
 LICENSE 
 README.md 

I'm happy to save you some work and just snag a copy from your fork and push your folder changes (plus the gitignore) directly.

**Comment by dtherrick** [comment]
OK - added those four files back to my repo. So sorry for the inconvenience!! This should cover it all now.

Thanks again - let me know if you have any other needs or questions!

**Comment by cjdinger** [comment]
@dtherrick Some things were still out of sync -- so I just manually added files from your fork.  Now your fork is probably horribly mismatched, but the master repo should have the right content.  Check it out,

**Pull request closed without merging**
